### PR TITLE
Lm01/solution

### PR DESCRIPTION
**Pull request by MicFin**
Do not merge with master.  Create solution branch.

### CODE REVIEW

**Comment by BenGitsCode** [comment]
Does a solution branch make sense here? I only ask because this add solution doesn't seem to be adding an actual solution. Wouldn't the solution have to include differing commits that change the story?

**Comment by MicFin** [comment]
I see what you mean.  It could be improved.  The solution branch includes a folder and two files: `/game-of-gits`,  `game-of-gits/sad-tale.md` and `game-of-gits/the-stark-bunch.md`.

https://github.com/ga-wdi-boston/git#code-along-making-a-local-repository 
- the developers create the folder `game-of-gits` 
- the devlopers create the file `sad-tale.md` and add text to it.

https://github.com/ga-wdi-boston/git#removing-now-we-need-to-remove-files-previously-added
- the developers create the file  `game-of-gits/the-stark-bunch.md`
- the developers add text to it.

The developers delete the `game-of-gits/the-stark-bunch.md` and add other text to and then remove it from the `game-of-gits/sad-tale.md` but it seems like including those files in a solution branch would be ok.

I am fine with the solution as is, with added commits, or no solution as it was.

**Comment by BenGitsCode** [comment]
Great clarification Mike! And as you said, we previously had no solution branch at all (there is a solution but it's 2yrs old and is not in line master's diagnostic. AFAIK All repos are being updated with a solution branch no matter what, per process.  I'll check with a lead before pushing this, as I don't want to stomp that history blindly.

@payne-chris-r merge into the existing solution? or rename this solution and force push?

**Comment by payne-chris-r** [comment]
Woah. This solution looks old. I think the `lm01/solution` branch looks more accurate given what @MicFin has said. @gaand @jrhorn424 do you know more about this history than I? Is it ok to wax the old solution? Should we archive it? Process for archiving (if necessary)?

**Comment by jrhorn424** [comment]
Please do not wax it. @payne-chris-r Instead, rename it `archive/solution` for now. I'll take care of moving it to attic, eventually.

**Comment by payne-chris-r** [comment]
Moved to `archive/solution`

**Pull request closed without merging**
